### ISSUE TITLE
Missing clang resource directory

### ISSUE THREAD

**Issue by rwestberg** [alexmurray/ccls-snap#1]
When building ccls, it determines the location of the clang resource directory, which must also be present when running it: https://github.com/MaskRay/ccls/wiki/Install#clang-resource-directory - you can also see this when launching in verbose mode:

```
initialize.cc:323 I use -resource-dir=/usr/lib/llvm-7/lib/clang/7.0.0`
```

These files are not present inside the snap folder, and thus ccls fails on anything but the most simple source files.

I'm not quite sure how to test this locally (snapcraft refuses to run in my ubuntu 18.04 VM) but I think it could be a matter of simply adding `libclang-common-7-dev` to stage-packages:

```
$ dpkg --search /usr/lib/llvm-7/lib/clang/7.0.0/include/stdint.h 
libclang-common-7-dev: /usr/lib/llvm-7/lib/clang/7.0.0/include/stdint.h
```

**Comment by alexmurray** [comment]
Thanks for the bug report - this is not easy to solve since just staging this means it ends up with the rest of the snap's contents - so actually is in `/snap/ccls/current//usr/lib/llvm-7/lib/clang/7.0.0` - and so ccls would need to know that the resourceDir is actually `/snap/ccls/current//usr/lib/llvm-7/lib/clang/7.0.0` - we could try and run ccls via a wrapper-script which does something like:
```
ccls --init '{ "clang": { "resourceDir": "/snap/ccls/current//usr/lib/llvm-7/lib/clang/7.0.0" } }
```

But this would then stop users supplying their own `--init` arguments to ccls. I will have a think about other ways which this could possibly be solved.

**Comment by rwestberg** [comment]
Thanks for taking a look! thought there was some sort of file system overlaying going on in a snap, but I guess that's not how it works indeed. Right, in that case modifying the CLANG_RESOURCE_DIR looks like a good approach to just change the default location.

**Comment by alexmurray** [comment]
Turns out https://github.com/alexmurray/ccls-snap/commit/88eae2d7ad84deb7defea5b5dab61ef02711cb05 is not as good since this makes ccls think the file is actually at `/usr/lib/llvm-7/...` but from the host system it is not so this has been reverted back to keep the original fix in https://github.com/alexmurray/ccls-snap/commit/1c05c17f253ab51d505490bb4aeb377306a93136 - closing this as fixed, please feel free to reopen or create a new issue if you notice any problems.

**Comment by rwestberg** [comment]
Tried the `--edge` version just now and it seems to be working fine, the resource dir looks correct.

Not sure it warrants a separate issue, but I do have to run it in `--devmode` as well to give it access to my toolchain include files which are outside of `home` - not sure how common that is in other projects though. Not sure what could be done about it either though, other than making it a "classic" snap.

Anyway, thanks for fixing!

**Comment by alexmurray** [comment]
Great :)

Yes that is a separate issue - I am currently trying to figure out if this can be done without having to resort to it being a classic snap - https://forum.snapcraft.io/t/access-to-system-header-files-for-a-strictly-confined-snap/11662/5

**Comment by rwestberg** [comment]
Ah I see, yeah, some sort of at least read-only access to the entire hostfs would be a nice capability.. Specific access to /usr/include etc wouldn't work in my case unfortunately, I'm using a separate toolchain in a completely different directory. But perhaps it would be good enough for most cases, and there's always --devmode for the more uncommon setups.. :)

**Comment by alexmurray** [comment]
Oh well that is interesting feedback - perhaps it's best just to go classic?

**Comment by rwestberg** [comment]
Yeah, I suspect it may be hard to maintain a specific list of allowed host directories, there's already a few different ones for system toolchains in default locations:

libc++-7-dev:amd64: /usr/lib/llvm-7/include/c++/v1/experimental/regex
libstdc++-7-dev:amd64: /usr/include/c++/7/regex

So unless you could open up at least the entire host `/usr`, perhaps classic is indeed best for now..

**Comment by alexmurray** [comment]
The `ccls` snap is now a classic snap - so there should be no need for --devmode, just --classic now:

    sudo snap refresh --classic ccls
